project_default_index:
    path: /
    defaults:
        _controller: EnhavoThemeBundle:Default:index
        path: /
        permanent: true

project_default_indexIpad:
    path: /index-ipad
    defaults:
        _controller: EnhavoThemeBundle:Default:indexIpad
        path: /index-ipad
        permanent: true

project_default_articles:
    path: /article-page
    defaults:
        _controller: EnhavoThemeBundle:Default:articles
        path: /article-page
        permanent: true

project_default_downloads:
    path: /downloads
    defaults:
        _controller: EnhavoThemeBundle:Default:downloads
        path: /downloads
        permanent: true

project_default_about:
    path: /about
    defaults:
        _controller: EnhavoThemeBundle:Default:aboutus
        path: /about
        permanent: true

project_default_article:
    path:     /news/{slug}
    defaults:
        _controller: EnhavoThemeBundle:Default:showArticle

project_default_page:
    path:     /{slug}
    defaults:
        _controller: EnhavoThemeBundle:Default:showPage

project_default_category:
    path:     /category/{slug}
    defaults:
        _controller: EnhavoThemeBundle:Default:showCategory
