Enhavo\Bundle\ThemeBundle\Model\Entity\Theme:
    attributes:
        id:
            groups: ['theme']
        key:
            groups: ['theme']
        active:
            groups: ['theme']

Enhavo\Bundle\ThemeBundle\Model\Theme:
    attributes:
        meta:
            groups: ['theme']
        webpack:
            groups: ['theme']
        template:
            groups: ['theme']
        block:
            groups: ['theme']

Enhavo\Bundle\ThemeBundle\Model\Webpack:
    attributes:
        build:
            groups: ['theme']
        options:
            groups: ['theme']

Enhavo\Bundle\ThemeBundle\Model\Template:
    attributes:
        mapping:
            groups: ['theme']

Enhavo\Bundle\ThemeBundle\Model\Meta:
    attributes:
        name:
            groups: ['theme']
        image:
            groups: ['theme']
        description:
            groups: ['theme']

Enhavo\Bundle\ThemeBundle\Model\Block:
    attributes:
        column_styles:
            groups: ['theme']
        templates:
            groups: ['theme']