services:
    enhavo_theme.box_render:
        class: Enhavo\Bundle\ThemeBundle\Box\BoxRendererExtension
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }

    enhavo_theme.box_collector:
        class: Enhavo\Bundle\ThemeBundle\Box\BoxCollector
        arguments:
            - '%enhavo_theme.boxes%'

    enhavo_theme.url_resolver:
        class: Enhavo\Bundle\AppBundle\Route\UrlResolver
        arguments:
          - '@router'
          - '%sylius.resources%'
          - '%enhavo_theme.route.url_resolver%'

    enhavo_theme.twig.url_resolver:
        class: Enhavo\Bundle\ThemeBundle\Twig\UrlResolver
        arguments:
            - '@enhavo_theme.url_resolver'
        tags:
            - { name: twig.extension }