enhavo_theme_theme_index:
    options:
        expose: true
    path: /enhavo/theme/theme/index
    methods: [GET]
    defaults:
        _controller: enhavo_theme.controller.theme:indexAction
        _sylius:
            viewer:
                actions:
                    create:
                        hidden: true
                        type: create
                        route: ~
                    filter:
                        type: filter

enhavo_theme_theme_update:
    options:
        expose: true
    path: /enhavo/theme/theme/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_theme.controller.theme:updateAction
        _sylius:
            viewer:
                actions_secondary:
                    delete:
                        type: delete
                        hidden: true
                        route: ~

enhavo_theme_theme_table:
    options:
        expose: true
    path: /enhavo/theme/theme/table
    methods: [GET,POST]
    defaults:
        _controller: enhavo_theme.controller.theme:tableAction
        _sylius:
            viewer:
                columns:
                    name:
                        property: theme.meta.name
                        width: 9
                        label: name
                        type: property
                    active:
                        property: active
                        width: 3
                        label: active
                        type: boolean

enhavo_theme_theme_delete:
    options:
        expose: true
    path: /enhavo/theme/theme/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_theme.controller.theme:deleteAction

enhavo_theme_theme_preview:
    options:
        expose: true
    path: /enhavo/theme/theme/preview
    methods: [GET]
    defaults:
        _controller: enhavo_theme.controller.theme:previewAction
        _sylius:
            viewer:

enhavo_theme_theme_resource_preview:
    options:
        expose: true
    path: /enhavo/theme/theme/resource/preview
    methods: [POST]
    defaults:
        _controller: enhavo_theme.controller.theme:previewResourceAction
        _sylius:
            viewer:
                strategy_options:
                    service: enhavo_article.controller.article:showResourceAction

