enhavo_theme_article_show:
    path: /article/{slug}
    defaults:
        _controller: EnhavoThemeBundle:Article:show

enhavo_theme_article_category:
    path: /category/{slug}
    defaults:
        _controller: EnhavoThemeBundle:Article:category

enhavo_theme_article_mobile:
    path: /mobile/{id}
    defaults:
        _controller: EnhavoThemeBundle:Article:category